// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WetterdatenImporter.Data;

#nullable disable

namespace WetterdatenImporter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322223918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WetterdatenImporter.Domain.Entities.EnvironmentDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AlderPollen")
                        .HasColumnType("REAL");

                    b.Property<double?>("BirchPollen")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EuropeanAqi")
                        .HasColumnType("REAL");

                    b.Property<int>("GebietId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("GrassPollen")
                        .HasColumnType("REAL");

                    b.Property<double?>("MugwortPollen")
                        .HasColumnType("REAL");

                    b.Property<double?>("NitrogenDioxide")
                        .HasColumnType("REAL");

                    b.Property<double?>("Ozone")
                        .HasColumnType("REAL");

                    b.Property<double?>("Pm10")
                        .HasColumnType("REAL");

                    b.Property<double?>("Pm2_5")
                        .HasColumnType("REAL");

                    b.Property<double?>("RagweedPollen")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GebietId", "Date", "Source")
                        .IsUnique();

                    b.ToTable("EnvironmentDaily", (string)null);
                });

            modelBuilder.Entity("WetterdatenImporter.Domain.Entities.MeasurementPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GebietId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GebietId")
                        .IsUnique();

                    b.ToTable("MeasurementPoint", (string)null);
                });

            modelBuilder.Entity("WetterdatenImporter.Domain.Entities.WeatherForecastDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ForecastDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ForecastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GebietId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PrecipitationSum")
                        .HasColumnType("REAL");

                    b.Property<double?>("RelativeHumidityMean")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("TemperatureMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("TemperatureMean")
                        .HasColumnType("REAL");

                    b.Property<double?>("TemperatureMin")
                        .HasColumnType("REAL");

                    b.Property<int?>("WeatherCode")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WindSpeedMax")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GebietId", "ForecastDate", "Source", "ForecastRunAt")
                        .IsUnique();

                    b.ToTable("WeatherForecastDaily", (string)null);
                });

            modelBuilder.Entity("WetterdatenImporter.Domain.Entities.WeatherObservedDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("GebietId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PrecipitationSum")
                        .HasColumnType("REAL");

                    b.Property<double?>("RelativeHumidityMean")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("TemperatureMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("TemperatureMean")
                        .HasColumnType("REAL");

                    b.Property<double?>("TemperatureMin")
                        .HasColumnType("REAL");

                    b.Property<int?>("WeatherCode")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WindSpeedMax")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GebietId", "Date", "Source")
                        .IsUnique();

                    b.ToTable("WeatherObservedDaily", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
