// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.AccidentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AccidentsHotspotAdjusted")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int?>("AccidentsTotalEstimated")
                        .HasColumnType("integer");

                    b.Property<int?>("AreaId")
                        .HasColumnType("integer");

                    b.Property<string>("DistrictBasis")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<int?>("FatalitiesEstimated")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HotspotFactor")
                        .HasColumnType("decimal(8,4)");

                    b.Property<int?>("InjuredEstimated")
                        .HasColumnType("integer");

                    b.Property<int?>("PopulationEstimated")
                        .HasColumnType("integer");

                    b.Property<int?>("PostalCodeCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RatePer10000Weighted")
                        .HasColumnType("decimal(8,4)");

                    b.Property<int?>("ReferenceYear")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("AccidentHistories", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PostalCodeId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("RiskSummer")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("RiskWinter")
                        .HasColumnType("decimal(5,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PostalCodeId");

                    b.ToTable("Attractions", (string)null);
                });

            modelBuilder.Entity("Core.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId")
                        .IsUnique();

                    b.HasIndex("DistrictName")
                        .IsUnique();

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExpectedVisitors")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PostalCodeId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PostalCodeId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<int?>("AttractionId")
                        .HasColumnType("integer");

                    b.Property<int>("IncidentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCodeId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("IncidentTypeId");

                    b.HasIndex("LocationTypeId");

                    b.HasIndex("PostalCodeId");

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("Core.Entities.IncidentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IncidentTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<decimal?>("SeverityMax")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("SeverityMean")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("SeverityMin")
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("IncidentTypeName")
                        .IsUnique();

                    b.ToTable("IncidentTypes", (string)null);
                });

            modelBuilder.Entity("Core.Entities.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocationTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeName")
                        .IsUnique();

                    b.ToTable("LocationTypes", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PostalCodeId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PostalCodeId");

                    b.ToTable("Municipalities", (string)null);
                });

            modelBuilder.Entity("Core.Entities.NursingHome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PostalCodeId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PostalCodeId");

                    b.ToTable("NursingHomes", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Population", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeStructure")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("integer");

                    b.Property<int>("ResidentCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("MunicipalityId");

                    b.ToTable("Populations", (string)null);
                });

            modelBuilder.Entity("Core.Entities.PostalCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("Plz")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("character varying(10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("Plz")
                        .IsUnique();

                    b.ToTable("PostalCodes", (string)null);
                });

            modelBuilder.Entity("Core.Entities.PublicHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsSchoolBreak")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("PublicHolidays", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(8,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("RiskScore")
                        .HasColumnType("decimal(8,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<decimal?>("ScoreAccident")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("ScoreEvent")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("ScoreHoliday")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("ScoreTraffic")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("ScoreWeather")
                        .HasColumnType("decimal(8,4)");

                    b.Property<DateTime>("WindowFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WindowTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Traffic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageVehicleSpeed")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("SegmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrafficStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("TravelTime")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("SegmentId");

                    b.ToTable("Traffics", (string)null);
                });

            modelBuilder.Entity("Core.Entities.TrafficAccident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("SegmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("SegmentId");

                    b.ToTable("TrafficAccidents", (string)null);
                });

            modelBuilder.Entity("Core.Entities.TrafficConstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("SegmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("SegmentId");

                    b.ToTable("TrafficConstructions", (string)null);
                });

            modelBuilder.Entity("Core.Entities.TrafficHotspot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CriticalityWeight")
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FreeFlowSpeedKph")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("HotspotName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<bool?>("IsCommuter")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsTouristic")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LengthKm")
                        .HasColumnType("decimal(8,3)");

                    b.Property<string>("LinkId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RoadType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("LinkId")
                        .IsUnique();

                    b.ToTable("TrafficHotspots", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AirQuality")
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("IsForecast")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ParticulateMatter")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("PollenBirch")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("PollenGrass")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("PollenTotal")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("PostalCodeId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("Precipitation")
                        .HasColumnType("decimal(6,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<decimal?>("Snow")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Visibility")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("WindSpeed")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("PostalCodeId");

                    b.ToTable("Weathers", (string)null);
                });

            modelBuilder.Entity("Core.Entities.AccidentHistory", b =>
                {
                    b.HasOne("Core.Entities.District", "District")
                        .WithMany("AccidentHistories")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Core.Entities.Attraction", b =>
                {
                    b.HasOne("Core.Entities.PostalCode", "PostalCode")
                        .WithMany("Attractions")
                        .HasForeignKey("PostalCodeId")
                        .HasPrincipalKey("Plz")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PostalCode");
                });

            modelBuilder.Entity("Core.Entities.Event", b =>
                {
                    b.HasOne("Core.Entities.PostalCode", "PostalCode")
                        .WithMany("Events")
                        .HasForeignKey("PostalCodeId")
                        .HasPrincipalKey("Plz")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PostalCode");
                });

            modelBuilder.Entity("Core.Entities.Incident", b =>
                {
                    b.HasOne("Core.Entities.Attraction", "Attraction")
                        .WithMany("Incidents")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.IncidentType", "IncidentType")
                        .WithMany("Incidents")
                        .HasForeignKey("IncidentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.LocationType", "LocationType")
                        .WithMany("Incidents")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.PostalCode", "PostalCode")
                        .WithMany("Incidents")
                        .HasForeignKey("PostalCodeId")
                        .HasPrincipalKey("Plz")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attraction");

                    b.Navigation("IncidentType");

                    b.Navigation("LocationType");

                    b.Navigation("PostalCode");
                });

            modelBuilder.Entity("Core.Entities.Municipality", b =>
                {
                    b.HasOne("Core.Entities.PostalCode", "PostalCode")
                        .WithMany("Municipalities")
                        .HasForeignKey("PostalCodeId")
                        .HasPrincipalKey("Plz")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PostalCode");
                });

            modelBuilder.Entity("Core.Entities.NursingHome", b =>
                {
                    b.HasOne("Core.Entities.PostalCode", "PostalCode")
                        .WithMany("NursingHomes")
                        .HasForeignKey("PostalCodeId")
                        .HasPrincipalKey("Plz")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PostalCode");
                });

            modelBuilder.Entity("Core.Entities.Population", b =>
                {
                    b.HasOne("Core.Entities.Municipality", "Municipality")
                        .WithMany("Populations")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Core.Entities.PostalCode", b =>
                {
                    b.HasOne("Core.Entities.District", "District")
                        .WithMany("PostalCodes")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Core.Entities.Result", b =>
                {
                    b.HasOne("Core.Entities.District", "District")
                        .WithMany("Results")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Core.Entities.Traffic", b =>
                {
                    b.HasOne("Core.Entities.District", "District")
                        .WithMany("Traffics")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.TrafficHotspot", "Segment")
                        .WithMany("Traffics")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Core.Entities.TrafficAccident", b =>
                {
                    b.HasOne("Core.Entities.District", "District")
                        .WithMany("TrafficAccidents")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.TrafficHotspot", "Segment")
                        .WithMany("TrafficAccidents")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Core.Entities.TrafficConstruction", b =>
                {
                    b.HasOne("Core.Entities.District", "District")
                        .WithMany("TrafficConstructions")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.TrafficHotspot", "Segment")
                        .WithMany("TrafficConstructions")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Core.Entities.TrafficHotspot", b =>
                {
                    b.HasOne("Core.Entities.District", "District")
                        .WithMany("TrafficHotspots")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Core.Entities.Weather", b =>
                {
                    b.HasOne("Core.Entities.PostalCode", "PostalCode")
                        .WithMany("Weathers")
                        .HasForeignKey("PostalCodeId")
                        .HasPrincipalKey("Plz")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PostalCode");
                });

            modelBuilder.Entity("Core.Entities.Attraction", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Core.Entities.District", b =>
                {
                    b.Navigation("AccidentHistories");

                    b.Navigation("PostalCodes");

                    b.Navigation("Results");

                    b.Navigation("TrafficAccidents");

                    b.Navigation("TrafficConstructions");

                    b.Navigation("TrafficHotspots");

                    b.Navigation("Traffics");
                });

            modelBuilder.Entity("Core.Entities.IncidentType", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Core.Entities.LocationType", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Core.Entities.Municipality", b =>
                {
                    b.Navigation("Populations");
                });

            modelBuilder.Entity("Core.Entities.PostalCode", b =>
                {
                    b.Navigation("Attractions");

                    b.Navigation("Events");

                    b.Navigation("Incidents");

                    b.Navigation("Municipalities");

                    b.Navigation("NursingHomes");

                    b.Navigation("Weathers");
                });

            modelBuilder.Entity("Core.Entities.TrafficHotspot", b =>
                {
                    b.Navigation("TrafficAccidents");

                    b.Navigation("TrafficConstructions");

                    b.Navigation("Traffics");
                });
#pragma warning restore 612, 618
        }
    }
}
